#!/usr/bin/env bash
# setup.sh — initializes a new Flutter project from flutter_starter.
#
# Usage:
#   1. Copy flutter_starter/ to your new project directory
#   2. Run: flutter create . --org com.example.yourcompany --project-name your_app_name
#   3. Run: bash setup.sh your_app_name
#
# What this script does:
#   - Replaces 'flutter_starter' with your app name in all Dart files
#   - Patches pubspec.yaml with required dependencies
#   - Runs flutter pub get in root and all packages

set -e

APP_NAME="${1}"

if [ -z "$APP_NAME" ]; then
  echo "Usage: bash setup.sh <app_name>"
  echo "Example: bash setup.sh myapp"
  exit 1
fi

echo "→ Replacing 'flutter_starter' with '$APP_NAME' in Dart files..."
find lib packages -name "*.dart" -exec sed -i '' "s/flutter_starter/$APP_NAME/g" {} \;

echo "→ Patching pubspec.yaml..."
# Append local package dependencies after the last existing dependency line.
# Assumes pubspec.yaml was generated by 'flutter create .' and contains
# a 'dependencies:' block with flutter and cupertino_icons.

# Add flutter_localizations under the flutter sdk dependency
sed -i '' '/sdk: flutter$/{
  /flutter_localizations/!{
    n
    /flutter_localizations/!i\\
  flutter_localizations:\\
    sdk: flutter
  }
}' pubspec.yaml 2>/dev/null || true

# Add package dependencies before dev_dependencies
DEPS="
  monitoring:
    path: packages/monitoring
  component_library:
    path: packages/component_library
  app_settings:
    path: packages/app_settings
  preferences_storage:
    path: packages/preferences_storage
  shared:
    path: packages/shared

  flutter_bloc: ^9.1.1
  package_info_plus: ^9.0.0"

# Insert before dev_dependencies:
python3 - <<PYEOF
import re

with open('pubspec.yaml', 'r') as f:
    content = f.read()

insert = """
  monitoring:
    path: packages/monitoring
  component_library:
    path: packages/component_library
  app_settings:
    path: packages/app_settings
  preferences_storage:
    path: packages/preferences_storage
  shared:
    path: packages/shared

  flutter_bloc: ^9.1.1
  package_info_plus: ^9.0.0
"""

# Insert flutter_localizations after 'sdk: flutter' (first occurrence, under dependencies)
content = re.sub(
    r'(dependencies:.*?flutter:\n    sdk: flutter)',
    r'\1\n  flutter_localizations:\n    sdk: flutter',
    content,
    count=1,
    flags=re.DOTALL
)

# Insert packages before dev_dependencies
content = content.replace('dev_dependencies:', insert + 'dev_dependencies:', 1)

with open('pubspec.yaml', 'w') as f:
    f.write(content)

print('  pubspec.yaml updated.')
PYEOF

echo "→ Running flutter pub get in root..."
flutter pub get

echo "→ Running flutter pub get in packages..."
for pkg in monitoring preferences_storage app_settings component_library; do
  echo "  packages/$pkg..."
  (cd "packages/$pkg" && flutter pub get)
done

echo ""
echo "✓ Done! Next steps:"
echo "  - lib/app/material_context.dart → replace 'const Placeholder()' with your home screen"
echo "  - lib/app/router/app_routes.dart → add your route constants"
echo "  - flutter run"
